### ISSUE TITLE
VMFleet change request to be able to use the existing Azue Stack Volumes

### ISSUE THREAD

**Issue by GITGW** [Azure/azurestack-solutionvalidation#1]
Need a synthetic workload tool that works with S2D storage in AzureStack. Purpose would be to run an IO profile across all R/W bands. Using these results would help in building a sizer tool for Pre-Sales.

**Comment by JohnHaskin** [comment]
@GITGW Hi Graham. We're looking at this as a long term item for VaaS with a 12+ month delivery so in the short term your best bet is to leverage the existing QuickStart templates for workloads. You can find those here:

- [Template](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-arm-templates) 
- [Marketplace: ](https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-marketplace)
